

HEAD https://broadcast.adpronet.com/radio/8010/radio.mp3
User-Agent: Dailymate Radio/1.0
Icy-MetaData: 1

###
HEAD https://stream.radio.co/sdfd68a101/listen
User-Agent: Dailymate Radio/1.0
Icy-MetaData: 1